"""initial schema

Revision ID: edd72b7c7c5d
Revises: 
Create Date: 2026-10-03 11:33:54.030379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd72b7c7c5d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('is_baseline', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_id'), 'assets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_table('assumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assumption_id', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('related_control_id', sa.String(length=100), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('is_baseline', sa.Boolean(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assumptions_assumption_id'), 'assumptions', ['assumption_id'], unique=False)
    op.create_index(op.f('ix_assumptions_id'), 'assumptions', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('change_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('affected_entities', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('potentially_breaks_assumptions', sa.Boolean(), nullable=True),
    sa.Column('affected_assumption_id', sa.String(length=100), nullable=True),
    sa.Column('affected_assumption_desc', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_events_id'), 'change_events', ['id'], unique=False)
    op.create_table('communication_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path_id', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('destination_id', sa.String(length=100), nullable=False),
    sa.Column('protocol', sa.String(length=50), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('passes_through', sa.JSON(), nullable=True),
    sa.Column('is_baseline', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_paths_id'), 'communication_paths', ['id'], unique=False)
    op.create_index(op.f('ix_communication_paths_path_id'), 'communication_paths', ['path_id'], unique=False)
    op.create_table('decay_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.String(length=100), nullable=False),
    sa.Column('property_desc', sa.String(length=500), nullable=False),
    sa.Column('baseline_protection', sa.Float(), nullable=True),
    sa.Column('current_protection', sa.Float(), nullable=True),
    sa.Column('decay_percent', sa.Float(), nullable=True),
    sa.Column('health_label', sa.String(length=50), nullable=True),
    sa.Column('contributors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decay_reports_id'), 'decay_reports', ['id'], unique=False)
    op.create_table('remediations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remediation_id', sa.String(length=100), nullable=False),
    sa.Column('repair_id', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('applied_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('target_entity', sa.String(length=200), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediations_id'), 'remediations', ['id'], unique=False)
    op.create_index(op.f('ix_remediations_remediation_id'), 'remediations', ['remediation_id'], unique=False)
    op.create_table('repair_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repair_id', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('security_improvement', sa.Float(), nullable=False),
    sa.Column('cost_effectiveness_ratio', sa.Float(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repair_recommendations_id'), 'repair_recommendations', ['id'], unique=False)
    op.create_table('security_controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('control_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_baseline', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_controls_control_id'), 'security_controls', ['control_id'], unique=False)
    op.create_index(op.f('ix_security_controls_id'), 'security_controls', ['id'], unique=False)
    op.create_table('security_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('control_id', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('protection_level', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_properties_id'), 'security_properties', ['id'], unique=False)
    op.create_index(op.f('ix_security_properties_property_id'), 'security_properties', ['property_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('control_protected_assets',
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['control_id'], ['security_controls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('control_id', 'asset_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('control_protected_assets')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_security_properties_property_id'), table_name='security_properties')
    op.drop_index(op.f('ix_security_properties_id'), table_name='security_properties')
    op.drop_table('security_properties')
    op.drop_index(op.f('ix_security_controls_id'), table_name='security_controls')
    op.drop_index(op.f('ix_security_controls_control_id'), table_name='security_controls')
    op.drop_table('security_controls')
    op.drop_index(op.f('ix_repair_recommendations_id'), table_name='repair_recommendations')
    op.drop_table('repair_recommendations')
    op.drop_index(op.f('ix_remediations_remediation_id'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_id'), table_name='remediations')
    op.drop_table('remediations')
    op.drop_index(op.f('ix_decay_reports_id'), table_name='decay_reports')
    op.drop_table('decay_reports')
    op.drop_index(op.f('ix_communication_paths_path_id'), table_name='communication_paths')
    op.drop_index(op.f('ix_communication_paths_id'), table_name='communication_paths')
    op.drop_table('communication_paths')
    op.drop_index(op.f('ix_change_events_id'), table_name='change_events')
    op.drop_table('change_events')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assumptions_id'), table_name='assumptions')
    op.drop_index(op.f('ix_assumptions_assumption_id'), table_name='assumptions')
    op.drop_table('assumptions')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
